setwd("D:/Coursera/ExProj2/ExData_proj2")
NEI<-readRDS("../exdata-data-NEI_data/summarySCC_PM25.rds")
v1<-aggregate(x=NEI$Emissions, by=list(category=NEI$year), FUN=sum)
plot(v1,type="o",xlab="year", ylab="Total Emision", main = "Total Emissions in the United States")
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()